import { PrismaClient } from '@prisma/client';

// Reuse a single PrismaClient instance across hot reloads (NestJS/Next.js dev
// servers, test watchers) to avoid exhausting PostgreSQL connections. This is
// the standard Prisma pattern for long-running Node processes with module
// reloading; in a normal production start it just runs once.
declare global {
  // eslint-disable-next-line no-var -- required for the hot-reload singleton pattern
  var __sigapPrisma: PrismaClient | undefined;
}

function createPrismaClient(): PrismaClient {
  return new PrismaClient({
    log: process.env.NODE_ENV === 'production' ? ['error', 'warn'] : ['error', 'warn', 'query'],
  });
}

/**
 * Configured PrismaClient singleton for the whole SIGAP monorepo.
 *
 * Connects as the `sigap_app` database role (see migration
 * 20260827190000_foundation): INSERT/SELECT only on `audit_log`, full CRUD on
 * every other foundation table. That split is enforced in PostgreSQL itself
 * (ADR-04 / critical control K-7) -- it does not depend on anything in this
 * file, and this client will get a permission-denied error from Postgres if
 * application code ever attempts `prisma.auditLog.update(...)` or
 * `prisma.auditLog.delete(...)`.
 *
 * Primary keys are UUID v7, generated by the calling application code before
 * every `create()` call -- not by this package and not by a database
 * default. There is intentionally no `@default(uuid())` anywhere in
 * prisma/schema.prisma (Prisma's built-in default generates UUID v4, which
 * would violate the "PK dibangkitkan aplikasi, terurut waktu" convention).
 * Callers are expected to supply `id` explicitly, e.g. using a UUIDv7 library
 * chosen at the application layer (apps/api).
 */
export const prisma: PrismaClient = globalThis.__sigapPrisma ?? createPrismaClient();

if (process.env.NODE_ENV !== 'production') {
  globalThis.__sigapPrisma = prisma;
}

export * from '@prisma/client';
export default prisma;
