-- ============================================================================
-- SIGAP -- Modul B (Access Review) migration
--
-- Hand-written (not `prisma migrate dev` output), same reason as the
-- foundation migration's partition-management functions below cannot be
-- generated by Prisma at all.
--
-- Source of truth: docs/04-TRD.md Sec 3.3 (Modul B ERD) and Sec 3.5/3.6
-- (design-decision table, mandatory indexes), docs/03-FRD.md FR-B-001..025,
-- docs/07-API-CONTRACT.md Sec 5, docs/10-TEST-PLAN.md Sec 3.2 (critical
-- controls K-1..K-4, K-9). Deliberate deviations from the ERD are called out
-- inline and summarized in packages/db/README.md.
--
-- APPLICATION-VERSION SAFETY: this migration only CREATEs new objects. It
-- adds no column to, and drops nothing from, any table created by the
-- foundation migration, so it is safe to apply before, during, or after any
-- apps/api rollout that does not yet know about Modul B.
--
-- CONCURRENTLY: every table in this file is created fresh in this same
-- migration and is empty for its entire duration (identical reasoning to the
-- foundation migration's header comment) -- CREATE INDEX CONCURRENTLY is not
-- needed here and, for the two mandatory snapshot_line indexes, cannot be
-- combined with the CREATE TABLE + PARTITION BY statements that precede them
-- in the same transaction anyway. CONCURRENTLY becomes mandatory starting
-- with the next migration that adds an index to snapshot_line, review_item,
-- or any other Modul B table built here once it holds production data.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Extensions
--
-- No new extension is required by Modul B. pgvector/pg_trgm/pgcrypto/btree_gin
-- were already installed by the foundation migration; pgcrypto is used below
-- by connector.encrypted_credentials (column-level encryption, see Sec 3).
-- unaccent still belongs to the Indonesian text-search configuration that
-- ships with document_chunk (Modul C, ADR-02) -- not installed here either.
-- ----------------------------------------------------------------------------

-- ----------------------------------------------------------------------------
-- 2. Enum types (docs/04-TRD.md Sec 3.3)
--
-- Real Postgres ENUM types, following the pattern the foundation migration
-- established (app_user_type, file_scan_status, notification_frequency):
-- closed, FR-mandated vocabularies become typed Prisma enums rather than
-- varchar + CHECK. Several are deliberately SHARED across tables where the
-- underlying concept is identical (risk_level_type, connector_type,
-- finding_status) -- a documented deviation from a literal per-column
-- reading of the ERD, which would otherwise redefine the same closed set
-- three or four different times. See packages/db/README.md.
-- ----------------------------------------------------------------------------
CREATE TYPE risk_level_type AS ENUM ('KRITIS', 'TINGGI', 'SEDANG', 'RENDAH');
CREATE TYPE hosting_type AS ENUM ('ON_PREMISE', 'SAAS', 'HIBRIDA');
CREATE TYPE review_frequency_type AS ENUM ('TRIWULANAN', 'SEMESTERAN', 'TAHUNAN');
CREATE TYPE entitlement_type AS ENUM ('PERAN', 'GRUP', 'IZIN', 'PROFIL');
-- Shared by connector.type (FR-B-003 / ADR-05 AccessConnector.type) and
-- access_snapshot.source (which connector type -- or MANUAL upload,
-- FR-B-004 -- produced this snapshot). Same closed set both places.
CREATE TYPE connector_type AS ENUM ('LDAP', 'JDBC', 'REST', 'SFTP', 'MANUAL');
CREATE TYPE access_snapshot_status AS ENUM ('MEMPROSES', 'SELESAI', 'GAGAL');
CREATE TYPE connector_test_result AS ENUM ('BERHASIL', 'GAGAL');
CREATE TYPE connector_run_status AS ENUM ('BERHASIL', 'GAGAL', 'SEDANG_BERJALAN');
CREATE TYPE campaign_type AS ENUM ('PERIODIK', 'AD_HOC', 'PEMICU_PERISTIWA');
-- FR-B-010 state diagram, Indonesian labels normalized to SCREAMING_SNAKE.
CREATE TYPE campaign_status AS ENUM (
  'DRAF', 'DIJADWALKAN', 'BERJALAN', 'MENUNGGU_SIGNOFF', 'SELESAI', 'DITUTUP', 'DIPERPANJANG', 'DIBATALKAN'
);
CREATE TYPE review_item_status AS ENUM ('BELUM_DIPUTUSKAN', 'DIPUTUSKAN', 'DIALIHKAN', 'ESKALASI');
-- FR-B-012 "Pilihan keputusan" table.
CREATE TYPE review_decision_type AS ENUM ('PERTAHANKAN', 'CABUT', 'UBAH', 'ALIHKAN');
CREATE TYPE revocation_action_type AS ENUM ('CABUT', 'UBAH');
-- FR-B-019 state diagram plus the FR-B-020 rule 3 terminal state
-- (Tidak Dapat Diverifikasi), which the mermaid diagram omits but the prose
-- requires.
CREATE TYPE revocation_ticket_status AS ENUM (
  'TERBUKA', 'DALAM_PROSES', 'MENUNGGU_VERIFIKASI', 'TERVERIFIKASI_TERTUTUP',
  'GAGAL_DIVERIFIKASI', 'DIKECUALIKAN', 'TIDAK_DAPAT_DIVERIFIKASI'
);
-- Shared lifecycle for sod_violation.status and access_anomaly.status --
-- both are "a bad condition was found, and can be open / excepted / resolved".
CREATE TYPE finding_status AS ENUM ('TERBUKA', 'DIKECUALIKAN', 'TERSELESAIKAN');
-- FR-B-007 detection table, codes AN-01..AN-08.
CREATE TYPE access_anomaly_code AS ENUM (
  'AN-01', 'AN-02', 'AN-03', 'AN-04', 'AN-05', 'AN-06', 'AN-07', 'AN-08'
);

-- ============================================================================
-- 3. application -- FR-B-001, docs/04-TRD.md Sec 3.3 ERD (followed exactly)
-- ============================================================================
CREATE TABLE application (
  id                     uuid PRIMARY KEY,
  code                   varchar(50) NOT NULL,
  name                   varchar(200) NOT NULL,
  owner_employee_id      uuid NOT NULL REFERENCES employee (id),
  tech_owner_employee_id uuid REFERENCES employee (id),
  criticality            risk_level_type NOT NULL,
  hosting_type           hosting_type NOT NULL,
  review_frequency       review_frequency_type NOT NULL,
  is_active              boolean NOT NULL DEFAULT true,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE application IS
  'Application registry subject to access review (FR-B-001). Columns follow docs/04-TRD.md Sec 3.3 ERD exactly. The FR-B-001 prose "Atribut" list additionally mentions uraian (description), jenis data yang diolah (data classification) and metode pengambilan data akses -- none of these are in the ERD column list, so none are added here; the last one is represented instead by the presence/type of a row in connector. Flagged in packages/db/README.md as needing a human decision on whether the ERD should gain these columns. Deactivation (rule 4) is via is_active, never a hard delete: history (snapshots, campaigns) referencing a deactivated application must remain queryable.';
COMMENT ON COLUMN application.owner_employee_id IS 'NOT NULL: FR-B-001 rule 1 -- every application MUST have an active-employee owner.';
COMMENT ON COLUMN application.tech_owner_employee_id IS 'Nullable in this migration; not explicitly required by FR-B-001, but FR-B-018 rule 1 falls back to this employee as the revocation ticket assignee when no other assignment rule applies.';

CREATE UNIQUE INDEX uq_application_code ON application (code);
CREATE INDEX idx_application_owner_employee_id ON application (owner_employee_id);
CREATE INDEX idx_application_tech_owner_employee_id ON application (tech_owner_employee_id);

-- ============================================================================
-- 4. entitlement_catalog -- FR-B-002, ERD followed exactly
-- ============================================================================
CREATE TABLE entitlement_catalog (
  id                   uuid PRIMARY KEY,
  application_id       uuid NOT NULL REFERENCES application (id),
  technical_code       varchar(200) NOT NULL,
  display_name         varchar(200) NOT NULL,
  business_description text,
  entitlement_type     entitlement_type NOT NULL,
  risk_level           risk_level_type NOT NULL,
  is_privileged        boolean NOT NULL DEFAULT false,
  is_financial         boolean NOT NULL DEFAULT false,
  is_categorized       boolean NOT NULL DEFAULT false,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE entitlement_catalog IS
  'Per-application entitlement catalog (FR-B-002). business_description is the mandatory non-technical explanation rule 1 refers to; NULL means it is missing (see is_categorized).';
COMMENT ON COLUMN entitlement_catalog.is_categorized IS
  'FR-B-002 rules 1-2 / TRD Sec 3.5 design note row 8: false means business_description is missing or unreviewed. New entitlements discovered on a snapshot are inserted with is_categorized = false ("Belum Dikategorikan") and route a notification to the application owner; the application, not a trigger, performs that insert-and-notify.';

CREATE UNIQUE INDEX uq_entitlement_catalog_app_technical_code ON entitlement_catalog (application_id, technical_code);
COMMENT ON INDEX uq_entitlement_catalog_app_technical_code IS
  'Not specified by the ERD; added deliberately so the same technical role/permission code cannot be registered twice under one application.';
CREATE INDEX idx_entitlement_catalog_application_id ON entitlement_catalog (application_id);
CREATE INDEX idx_entitlement_catalog_uncategorized ON entitlement_catalog (application_id) WHERE NOT is_categorized;

-- ============================================================================
-- 5. connector -- FR-B-003, ADR-05. Not detailed in the ERD relation diagram;
-- designed against FR-B-003 and the AccessConnector interface in ADR-05.
-- ============================================================================
CREATE TABLE connector (
  id                        uuid PRIMARY KEY,
  application_id            uuid NOT NULL REFERENCES application (id),
  type                      connector_type NOT NULL,
  name                      varchar(200) NOT NULL,
  config                    jsonb NOT NULL DEFAULT '{}'::jsonb,
  encrypted_credentials     bytea,
  schedule_cron             varchar(100),
  is_active                 boolean NOT NULL DEFAULT true,
  consecutive_failure_count smallint NOT NULL DEFAULT 0,
  last_tested_at            timestamptz,
  last_test_result          connector_test_result,
  last_run_at               timestamptz,
  last_run_status           connector_run_status,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_connector_failure_count CHECK (consecutive_failure_count >= 0)
);

COMMENT ON TABLE connector IS
  'Access data retrieval configuration per application (FR-B-003, ADR-05). Design decision, not in the ERD relation diagram with columns. type mirrors ADR-05''s AccessConnector.type union (ldap|jdbc|rest|sftp|manual), uppercased for this schema''s enum convention. Field-mapping configuration (ADR-05 rule 5) lives in config (jsonb), never in code. Rule 1 (read-only credentials, secrets storage, never shown after save) is implemented as column-level encryption via pgcrypto (encrypted_credentials, bytea) rather than a plaintext column -- the raw secret is written once by the connector service using pgp_sym_encrypt() with a passphrase from the secrets manager (never a literal in application code or this migration), and is only ever decrypted, in memory, by the connector execution service itself. No repository method should ever SELECT this column into a generic DTO. FR-B-003 exception path (three consecutive failures -> auto-disable + escalate) is implemented by the application flipping is_active and reading consecutive_failure_count; there is deliberately no DB trigger auto-flipping is_active on the count crossing 3, since disabling-and-escalating is a workflow action (it must also enqueue a notification), not a pure data invariant a CHECK can express. Gap flagged in packages/db/README.md "Hal yang perlu diputuskan manusia": a connector_run history table (FR-B-003 rule 3: per-execution start/end time, identity/entitlement counts, status) is NOT created here -- it is not one of the 15 tables this migration was scoped to build, so last_tested_at/last_run_at/last_run_status on this row only capture the MOST RECENT execution, not full history.';
COMMENT ON COLUMN connector.encrypted_credentials IS
  'pgcrypto pgp_sym_encrypt() ciphertext. Never selected into an API response; decrypted only inside the connector execution service. See table comment.';

CREATE INDEX idx_connector_application_id ON connector (application_id);
CREATE INDEX idx_connector_is_active ON connector (is_active);

-- ============================================================================
-- 6. access_snapshot -- FR-B-005, ERD followed exactly
-- ============================================================================
CREATE TABLE access_snapshot (
  id                uuid PRIMARY KEY,
  application_id    uuid NOT NULL REFERENCES application (id),
  captured_at       timestamptz NOT NULL,
  source            connector_type NOT NULL,
  captured_by       uuid REFERENCES app_user (id),
  identity_count    integer NOT NULL DEFAULT 0,
  entitlement_count integer NOT NULL DEFAULT 0,
  content_hash      varchar(64) NOT NULL,
  status            access_snapshot_status NOT NULL DEFAULT 'MEMPROSES',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_access_snapshot_content_hash CHECK (content_hash ~ '^[a-f0-9]{64}$'),
  CONSTRAINT chk_access_snapshot_counts CHECK (identity_count >= 0 AND entitlement_count >= 0)
);

COMMENT ON TABLE access_snapshot IS
  'Immutable point-in-time capture of one application''s identities and entitlements (FR-B-005, ADR-07). Rule 2 (snapshot cannot be edited; corrections are a new capture) is enforced at the application/repository layer, not by a database trigger -- unlike audit_log (ADR-04/K-7), snapshot immutability is not one of the ten critical controls this migration was asked to enforce at the database level (docs/10-TEST-PLAN.md Sec 3.2), so no reject-mutation trigger + privilege revoke was added here. Flagged in packages/db/README.md in case a future review wants the stronger guarantee.';
COMMENT ON COLUMN access_snapshot.captured_by IS
  'Nullable: unattended scheduled connector runs (ADR-08 connector-sync queue) have no human actor. Manual uploads (FR-B-004) and ad-hoc verification triggers (FR-B-021) populate this with the triggering app_user.';
COMMENT ON COLUMN access_snapshot.content_hash IS
  'SHA-256 hex digest over the full snapshot content (FR-B-005 rule 1 "sidik jari isi"), computed by the application once every snapshot_line row for this snapshot has been inserted.';

CREATE INDEX idx_access_snapshot_application_id ON access_snapshot (application_id);
CREATE INDEX idx_access_snapshot_app_captured_at ON access_snapshot (application_id, captured_at DESC);

-- ============================================================================
-- 7. snapshot_line -- ADR-07. Largest table in the system (~14.4M rows / 5
-- years per ADR-07's own volume estimate). Partitioned.
--
-- DEVIATION (documented, see also packages/db/README.md): ADR-07's
-- "Konsekuensi" paragraph (docs/04-TRD.md line 367) literally reads
-- "dipartisi berdasarkan snapshot_id dalam rentang bulanan" (partitioned BY
-- snapshot_id in monthly ranges). Taken completely literally this would mean
-- RANGE partitioning on a foreign-key UUIDv7 column with hand-computed
-- calendar-month boundary values encoded as UUID byte ranges -- fragile,
-- unreadable, and not how PostgreSQL declarative partitioning is normally
-- expressed. TRD Sec 3.5 row 6 describes the SAME decision as "partisi
-- berdasarkan rentang waktu" (partitioned by TIME range) for archival
-- convenience, which is the standard, literal reading of "monthly range
-- partitions". This migration partitions by `captured_at` (timestamptz), a
-- column DENORMALIZED onto snapshot_line from its parent
-- access_snapshot.captured_at at insert time -- the conventional PostgreSQL
-- implementation of "monthly partitions keyed on when the snapshot was
-- captured". Flagged for a docs/04-TRD.md ADR-07 wording clarification.
--
-- CONSEQUENCE OF PARTITIONING (documented): PostgreSQL requires every unique
-- constraint (hence the primary key) on a partitioned table to include the
-- partition key column. The primary key here is therefore (id, captured_at),
-- not `id` alone like every other table in this schema. A further
-- consequence: PostgreSQL cannot enforce a FOREIGN KEY that targets `id`
-- alone on a partitioned table, so every column elsewhere in this migration
-- that references a snapshot_line row (review_item.snapshot_line_id,
-- sod_violation''s entitlement pair, access_anomaly.snapshot_line_id) is a
-- plain uuid column WITHOUT a database-level FOREIGN KEY constraint --
-- referential integrity to snapshot_line is enforced at the application
-- repository layer. Adding captured_at to those referencing tables just to
-- satisfy a composite FK was rejected: for review_item it would mean adding a
-- column beyond the ERD''s fixed column list, which the task instructions for
-- this migration explicitly forbid ("ikuti nama tabel dan kolom di sana
-- persis").
--
-- NO DEFAULT PARTITION is created, by design: an INSERT into a month with no
-- partition yet MUST fail loudly instead of silently collecting in a
-- catch-all partition. See ensure_snapshot_line_partition() below for the
-- mechanism that keeps partitions provisioned ahead of need.
-- ============================================================================
CREATE TABLE snapshot_line (
  id             uuid NOT NULL,
  snapshot_id    uuid NOT NULL REFERENCES access_snapshot (id),
  captured_at    timestamptz NOT NULL,
  account_id     varchar(200) NOT NULL,
  account_name   varchar(200),
  entitlement_id uuid NOT NULL REFERENCES entitlement_catalog (id),
  employee_id    uuid REFERENCES employee (id),
  account_status varchar(50) NOT NULL,
  last_access_at timestamptz,
  granted_at     date,
  granted_by     varchar(200),
  PRIMARY KEY (id, captured_at)
) PARTITION BY RANGE (captured_at);

COMMENT ON TABLE snapshot_line IS
  'One row per (account, entitlement) held at capture time (FR-B-005, ADR-07). Stored in full per snapshot, never as a diff -- ADR-07''s whole point is that "what was the state on date X" queries must not be reconstructed from a change log. Partitioned monthly by captured_at; see the deviation note above the CREATE TABLE statement for why captured_at (not snapshot_id) is the partition key, and why inbound references to this table have no database-level FOREIGN KEY.';
COMMENT ON COLUMN snapshot_line.captured_at IS
  'Denormalized copy of the parent access_snapshot.captured_at, set by the application at insert time to the same value used on the corresponding access_snapshot row. Exists solely to serve as the partition key. The invariant "always equal to access_snapshot.captured_at for the same snapshot_id" is an application responsibility (all lines for one snapshot are inserted in the same ingestion batch using the value already read from access_snapshot), not database-enforced -- a CHECK constraint cannot reference another table in PostgreSQL.';
COMMENT ON COLUMN snapshot_line.employee_id IS
  'Nullable: FR-B-006 rule 4 -- accounts that cannot be mapped to an employee are flagged "Tanpa Pemilik", not rejected.';

-- Only the two indexes mandated by docs/04-TRD.md Sec 3.6 (line 813) are
-- added here, deliberately. This table is projected to reach ~14.4 million
-- rows over 5 years, and every additional index multiplies write and storage
-- cost across the whole partition set. A per-snapshot uniqueness guard on
-- (snapshot_id, account_id, entitlement_id) was considered and rejected for
-- the same reason; that data-quality check is enforced by the
-- connector/upload ingestion pipeline instead.
CREATE INDEX idx_snapshot_line_snapshot_employee ON snapshot_line (snapshot_id, employee_id);
CREATE INDEX idx_snapshot_line_snapshot_entitlement ON snapshot_line (snapshot_id, entitlement_id);

-- ----------------------------------------------------------------------------
-- 7.1 Partition management (ADR-07)
--
-- No pg_cron dependency is assumed (not part of the installed extension
-- list). These functions are meant to be invoked periodically by the
-- `scheduled-jobs` BullMQ queue (ADR-08) from apps/api -- wiring that
-- invocation up is out of scope for this migration (packages/db only, per
-- this task''s "Batas kerja"); see packages/db/README.md.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION ensure_snapshot_line_partition(p_month_start date)
RETURNS void AS $$
DECLARE
  v_partition_name text := 'snapshot_line_' || to_char(p_month_start, 'YYYY_MM');
  v_month_end       date := (p_month_start + INTERVAL '1 month')::date;
BEGIN
  IF p_month_start <> date_trunc('month', p_month_start)::date THEN
    RAISE EXCEPTION 'p_month_start harus tanggal pertama suatu bulan, diterima: %', p_month_start;
  END IF;

  EXECUTE format(
    'CREATE TABLE IF NOT EXISTS public.%I PARTITION OF public.snapshot_line FOR VALUES FROM (%L) TO (%L)',
    v_partition_name, p_month_start, v_month_end
  );
END;
$$ LANGUAGE plpgsql SET search_path = pg_catalog, public;

COMMENT ON FUNCTION ensure_snapshot_line_partition(date) IS
  'Idempotently creates the monthly range partition of snapshot_line covering [p_month_start, p_month_start + 1 month). p_month_start must be the first day of a month. Safe to call repeatedly (CREATE TABLE IF NOT EXISTS).';

CREATE OR REPLACE FUNCTION ensure_snapshot_line_partitions_ahead(p_months_ahead integer DEFAULT 3)
RETURNS void AS $$
DECLARE
  v_month date := date_trunc('month', now())::date;
  i        integer;
BEGIN
  FOR i IN 0..p_months_ahead LOOP
    PERFORM ensure_snapshot_line_partition((v_month + (i || ' months')::interval)::date);
  END LOOP;
END;
$$ LANGUAGE plpgsql SET search_path = pg_catalog, public;

COMMENT ON FUNCTION ensure_snapshot_line_partitions_ahead(integer) IS
  'Creates the current-month partition of snapshot_line plus p_months_ahead future monthly partitions, skipping any that already exist. Intended to be called on a recurring schedule (e.g. monthly) so a partition always exists before data for it arrives -- an INSERT into a month with no partition fails outright by design (see the comment block above CREATE TABLE snapshot_line).';

REVOKE EXECUTE ON FUNCTION ensure_snapshot_line_partition(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION ensure_snapshot_line_partitions_ahead(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ensure_snapshot_line_partition(date) TO sigap_app;
GRANT EXECUTE ON FUNCTION ensure_snapshot_line_partitions_ahead(integer) TO sigap_app;

-- Bootstrap: current calendar year plus a 3-month lookahead buffer, so this
-- migration alone is sufficient for development/staging without waiting on a
-- scheduled job. Earlier months are intentionally NOT pre-created -- there is
-- no data yet, and the "no default partition" intent above means a
-- historical backfill must explicitly provision the months it needs via
-- ensure_snapshot_line_partition(), surfacing missing-partition gaps
-- immediately instead of silently absorbing them into a catch-all partition.
DO $$
DECLARE
  v_month date := date_trunc('year', now())::date;
  v_end   date := (date_trunc('month', now())::date + INTERVAL '3 months')::date;
BEGIN
  WHILE v_month <= v_end LOOP
    PERFORM ensure_snapshot_line_partition(v_month);
    v_month := (v_month + INTERVAL '1 month')::date;
  END LOOP;
END
$$;

-- ============================================================================
-- 8. review_campaign -- FR-B-008..010, ERD followed exactly
-- ============================================================================
CREATE TABLE review_campaign (
  id                   uuid PRIMARY KEY,
  code                 varchar(50) NOT NULL,
  name                 varchar(200) NOT NULL,
  campaign_type        campaign_type NOT NULL,
  start_date           date NOT NULL,
  due_date             date NOT NULL,
  reviewer_rule        jsonb NOT NULL,
  fallback_reviewer_id uuid NOT NULL REFERENCES app_user (id),
  status               campaign_status NOT NULL DEFAULT 'DRAF',
  extension_count      smallint NOT NULL DEFAULT 0,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_review_campaign_due_after_start CHECK (due_date >= start_date),
  CONSTRAINT chk_review_campaign_extension_count CHECK (extension_count BETWEEN 0 AND 2)
);

COMMENT ON TABLE review_campaign IS
  'Access review campaign (FR-B-008..010). status default DRAF is a workflow starting state (like review_item.status below), not a "decision" field -- critical control K-2 only concerns review_decision.decision, which deliberately has no default (see Sec 12). chk_review_campaign_extension_count enforces FR-B-010 rule 1''s "maksimum dua kali" ceiling at the database level.';
COMMENT ON COLUMN review_campaign.fallback_reviewer_id IS 'NOT NULL: FR-B-009 rule 1 -- the fallback reviewer is mandatory campaign configuration, not optional.';

CREATE UNIQUE INDEX uq_review_campaign_code ON review_campaign (code);
CREATE INDEX idx_review_campaign_fallback_reviewer_id ON review_campaign (fallback_reviewer_id);
CREATE INDEX idx_review_campaign_status ON review_campaign (status);

-- ============================================================================
-- 9. campaign_scope -- FR-B-008. Not detailed in the ERD relation diagram;
-- one row per application included in a campaign''s scope, carrying the
-- filter criteria (org unit / job title / entitlement risk level / privileged
-- flag / anomaly codes) narrowing that application''s population, per
-- FR-B-008''s "Filter cakupan yang tersedia" list. Supports the FR-B-008
-- rule 2 launch preview (item/reviewer counts) via item_count.
-- ============================================================================
CREATE TABLE campaign_scope (
  id             uuid PRIMARY KEY,
  campaign_id    uuid NOT NULL REFERENCES review_campaign (id),
  application_id uuid NOT NULL REFERENCES application (id),
  scope_filter   jsonb NOT NULL DEFAULT '{}'::jsonb,
  item_count     integer,
  created_at     timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE campaign_scope IS
  'Design decision (FR-B-008): one row per application in a campaign''s scope. scope_filter holds the org-unit/job-title/risk-level/is_privileged/anomaly-code narrowing criteria from the "Filter cakupan yang tersedia" list. item_count is a cache populated at launch-preview and launch time (rule 2), not a live-computed column.';

CREATE UNIQUE INDEX uq_campaign_scope_campaign_application ON campaign_scope (campaign_id, application_id);
CREATE INDEX idx_campaign_scope_campaign_id ON campaign_scope (campaign_id);

-- ============================================================================
-- 10. review_item -- FR-B-011, ERD followed exactly
-- ============================================================================
CREATE TABLE review_item (
  id               uuid PRIMARY KEY,
  campaign_id      uuid NOT NULL REFERENCES review_campaign (id),
  snapshot_line_id uuid NOT NULL,
  reviewer_id      uuid NOT NULL REFERENCES app_user (id),
  layer_no         smallint NOT NULL DEFAULT 1,
  status           review_item_status NOT NULL DEFAULT 'BELUM_DIPUTUSKAN',
  is_flagged       boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_review_item_layer_no CHECK (layer_no BETWEEN 1 AND 2)
);

COMMENT ON TABLE review_item IS
  'One review item per (identity, entitlement) combination in a campaign''s scope (FR-B-011). status DEFAULT ''BELUM_DIPUTUSKAN'' is an allowed workflow default (critical control K-2 exempts review_item.status, applying only to review_decision.decision -- see Sec 12).';
COMMENT ON COLUMN review_item.snapshot_line_id IS
  'References snapshot_line(id) but carries NO database FOREIGN KEY constraint -- snapshot_line is partitioned and its primary key is the composite (id, captured_at); see the deviation note above CREATE TABLE snapshot_line (Sec 7). Referential integrity to snapshot_line is enforced in the application repository layer.';

CREATE INDEX idx_review_item_worklist ON review_item (campaign_id, reviewer_id, status);
CREATE INDEX idx_review_item_snapshot_line_id ON review_item (snapshot_line_id);

-- ============================================================================
-- 11. review_decision -- FR-B-012..014, ERD followed exactly.
-- Critical controls K-2, K-3, K-4.
-- ============================================================================
CREATE TABLE review_decision (
  id             uuid PRIMARY KEY,
  review_item_id uuid NOT NULL REFERENCES review_item (id),
  -- K-2 (FR-B-012 rule 1): NO DEFAULT on this column, deliberately. Absence
  -- of a decision is represented by the absence of a review_decision row
  -- (review_item.status stays BELUM_DIPUTUSKAN), never by a default value
  -- here that a reviewer could leave unchanged.
  decision       review_decision_type NOT NULL,
  -- K-3 (FR-B-012 rule 2-3): see chk_review_decision_reason_format and
  -- chk_review_decision_reason_required below. Nullable because Pertahankan
  -- on a non-privileged, non-high-risk item does not require a reason
  -- (FR-B-012 rule 3''s "walaupun keputusannya Pertahankan" carve-in for
  -- privileged/high-risk items depends on the referenced entitlement''s
  -- risk_level/is_privileged flags, which this table cannot see without a
  -- join -- that conditional requirement is enforced by the application
  -- repository, not by this CHECK).
  reason         text,
  decided_by     uuid NOT NULL REFERENCES app_user (id),
  on_behalf_of   uuid REFERENCES app_user (id),
  decided_at     timestamptz NOT NULL DEFAULT now(),
  -- K-4 (FR-B-013 rule 5): NOT NULL DEFAULT false, so every row explicitly
  -- states whether it came from a bulk action.
  bulk_applied   boolean NOT NULL DEFAULT false,
  seconds_spent  integer NOT NULL DEFAULT 0,
  CONSTRAINT chk_review_decision_seconds_spent CHECK (seconds_spent >= 0),
  -- K-3: length >= 10 (after trimming) AND not a single repeated character,
  -- applied whenever reason IS NOT NULL -- i.e. for EVERY decision type that
  -- supplies a reason, including Pertahankan, not only Cabut. The regex
  -- backreference \1 matches PostgreSQL''s ARE regex dialect (supported by
  -- the ~ / !~ operators, unlike SIMILAR TO).
  CONSTRAINT chk_review_decision_reason_format CHECK (
    reason IS NULL OR (length(btrim(reason)) >= 10 AND reason !~ '^(.)\1*$')
  ),
  -- K-3 / FR-B-012 table: Cabut, Ubah and Alihkan always require a reason;
  -- Pertahankan''s conditional requirement (privileged/high-risk items) is
  -- application-enforced, as noted on the reason column above.
  CONSTRAINT chk_review_decision_reason_required CHECK (
    decision = 'PERTAHANKAN' OR reason IS NOT NULL
  )
);

COMMENT ON TABLE review_decision IS
  'Reviewer decision for one review_item (FR-B-012). At most one row per review_item (uq_review_decision_review_item_id below), matching the ERD''s zero-or-one cardinality: FR-B-012 rule 5 allows a decision to be changed while the campaign is unsigned, which this schema models as an UPDATE in place (decided_at/decided_by/reason overwritten), with the change history captured by the audit_log write that must accompany every such UPDATE (CLAUDE.md rule 2), not by keeping multiple review_decision rows per item.';

CREATE UNIQUE INDEX uq_review_decision_review_item_id ON review_decision (review_item_id);
CREATE INDEX idx_review_decision_decided_by ON review_decision (decided_by);

-- ============================================================================
-- 12. campaign_signoff -- FR-B-015. Not detailed in the ERD relation
-- diagram. Critical control K-9.
-- ============================================================================
CREATE TABLE campaign_signoff (
  id                  uuid PRIMARY KEY,
  campaign_id         uuid NOT NULL REFERENCES review_campaign (id),
  signed_by           uuid NOT NULL REFERENCES app_user (id),
  layer_no            smallint NOT NULL DEFAULT 1,
  signed_at           timestamptz NOT NULL DEFAULT now(),
  ip_address          varchar(45) NOT NULL,
  decision_counts     jsonb NOT NULL,
  -- K-9: content fingerprint over the exact set of decisions being signed
  -- (FR-B-015 rule 3 "sidik jari kriptografis atas kumpulan keputusan").
  content_fingerprint varchar(64) NOT NULL,
  is_active           boolean NOT NULL DEFAULT true,
  reopened_at         timestamptz,
  reopened_by         uuid REFERENCES app_user (id),
  reopen_reason       text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_campaign_signoff_layer_no CHECK (layer_no BETWEEN 1 AND 2),
  CONSTRAINT chk_campaign_signoff_fingerprint CHECK (content_fingerprint ~ '^[a-f0-9]{64}$'),
  -- FR-B-015 rule 4: reopening always carries who/when/why, and flips
  -- is_active so the row is superseded, not deleted -- "sign-off sebelumnya
  -- tetap tersimpan". All four reopen fields move together, never partially.
  CONSTRAINT chk_campaign_signoff_reopen_consistency CHECK (
    (reopened_at IS NULL AND reopened_by IS NULL AND reopen_reason IS NULL AND is_active)
    OR
    (reopened_at IS NOT NULL AND reopened_by IS NOT NULL AND reopen_reason IS NOT NULL AND NOT is_active)
  )
);

COMMENT ON TABLE campaign_signoff IS
  'Design decision (FR-B-015): one row per (campaign, signer, layer). K-9 is implemented by content_fingerprint (SHA-256 hex over the exact decision set being signed, computed by the application before insert -- the same discipline as uploaded_file.sha256 and audit_log.hash) plus decision_counts (counts per decision type, rule 3). Reopening (rule 4) never deletes or updates content_fingerprint/decision_counts in place; it sets is_active = false and the reopened_* columns on the SAME row (so the original signed content stays intact and queryable), and a fresh campaign_signoff row is inserted once re-review is signed again. RA-03 two-layer campaigns (rule 5) are modeled with layer_no; the "layer 2 opens only after layer 1 completes" gate is an application workflow check, not a database constraint, since it requires knowing every layer-1 reviewer''s completion state.';

CREATE UNIQUE INDEX uq_campaign_signoff_active ON campaign_signoff (campaign_id, signed_by, layer_no) WHERE is_active;
CREATE INDEX idx_campaign_signoff_campaign_id ON campaign_signoff (campaign_id);

-- ============================================================================
-- 13. revocation_ticket -- FR-B-018..020, ERD followed exactly.
-- Critical control K-1.
-- ============================================================================
CREATE TABLE revocation_ticket (
  id                      uuid PRIMARY KEY,
  decision_id             uuid NOT NULL REFERENCES review_decision (id),
  ticket_no               varchar(50) NOT NULL,
  application_id          uuid NOT NULL REFERENCES application (id),
  entitlement_id          uuid NOT NULL REFERENCES entitlement_catalog (id),
  account_id              varchar(200) NOT NULL,
  action_type             revocation_action_type NOT NULL,
  assignee_id             uuid NOT NULL REFERENCES employee (id),
  sla_due_date            date NOT NULL,
  status                  revocation_ticket_status NOT NULL DEFAULT 'TERBUKA',
  verified_by_snapshot_id uuid REFERENCES access_snapshot (id),
  external_ticket_ref     varchar(200),
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  -- K-1 (FR-B-019 rule 1): the ONLY way this column can hold
  -- TERVERIFIKASI_TERTUTUP is together with a non-null
  -- verified_by_snapshot_id. There is no status value or column that lets a
  -- human close a ticket by claim; verified_by_snapshot_id can only be
  -- populated by the snapshot-driven verification job (FR-B-020) or the
  -- ad-hoc verification trigger (FR-B-021), both of which resolve it from an
  -- actual access_snapshot row -- never a manual free-text field.
  CONSTRAINT chk_revocation_ticket_verified_requires_snapshot CHECK (
    status <> 'TERVERIFIKASI_TERTUTUP' OR verified_by_snapshot_id IS NOT NULL
  )
);

COMMENT ON TABLE revocation_ticket IS
  'One ticket per signed-off Cabut/Ubah decision (FR-B-018). assignee_id references employee, not app_user: FR-B-018 rule 1 falls back to the application''s technical owner (an employee), and the executing IT staff member is not necessarily a SIGAP login account.';
COMMENT ON CONSTRAINT chk_revocation_ticket_verified_requires_snapshot ON revocation_ticket IS
  'Critical control K-1 (docs/10-TEST-PLAN.md Sec 3.2, FR-B-019 rule 1). Deliberately the only guard against manual closure at the database level: this migration adds no application-level "close" endpoint semantics, but the absence of any other column or status value that could satisfy TERVERIFIKASI_TERTUTUP without a real snapshot reference is itself the control.';

CREATE UNIQUE INDEX uq_revocation_ticket_ticket_no ON revocation_ticket (ticket_no);
CREATE INDEX idx_revocation_ticket_decision_id ON revocation_ticket (decision_id);
CREATE INDEX idx_revocation_ticket_application_id ON revocation_ticket (application_id);
CREATE INDEX idx_revocation_ticket_verified_by_snapshot_id ON revocation_ticket (verified_by_snapshot_id);
-- Not mandated by docs/04-TRD.md Sec 3.6 for Modul B (that section lists this
-- exact shape -- (pic/assignee, status, due_date) -- only for request_item,
-- Modul A''s analog). Added deliberately by the same reasoning: this is the
-- assignee''s SLA worklist, the hottest read path in FR-B-018/019/020.
CREATE INDEX idx_revocation_ticket_assignee_worklist ON revocation_ticket (assignee_id, status, sla_due_date);

-- ============================================================================
-- 14. sod_rule -- FR-B-024, ERD followed exactly
-- ============================================================================
CREATE TABLE sod_rule (
  id                   uuid PRIMARY KEY,
  code                 varchar(50) NOT NULL,
  name                 varchar(200) NOT NULL,
  risk_description     text NOT NULL,
  group_a              jsonb NOT NULL,
  group_b              jsonb NOT NULL,
  risk_level           risk_level_type NOT NULL,
  compensating_control text,
  is_active            boolean NOT NULL DEFAULT true,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE sod_rule IS
  'Segregation-of-duties conflict rule (FR-B-024). group_a/group_b hold entitlement-selection criteria (which may span applications, rule 1) as jsonb -- the same "criteria as data, not code" shape as review_campaign.reviewer_rule.';

CREATE UNIQUE INDEX uq_sod_rule_code ON sod_rule (code);
CREATE INDEX idx_sod_rule_is_active ON sod_rule (is_active) WHERE is_active;

-- ============================================================================
-- 15. sod_violation -- FR-B-024. Not detailed in the ERD relation diagram.
-- ============================================================================
CREATE TABLE sod_violation (
  id                      uuid PRIMARY KEY,
  rule_id                 uuid NOT NULL REFERENCES sod_rule (id),
  employee_id             uuid NOT NULL REFERENCES employee (id),
  entitlement_id_a        uuid NOT NULL REFERENCES entitlement_catalog (id),
  entitlement_id_b        uuid NOT NULL REFERENCES entitlement_catalog (id),
  detected_in_snapshot_id uuid NOT NULL REFERENCES access_snapshot (id),
  detected_at             timestamptz NOT NULL DEFAULT now(),
  status                  finding_status NOT NULL DEFAULT 'TERBUKA',
  resolved_at             timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_sod_violation_distinct_entitlements CHECK (entitlement_id_a <> entitlement_id_b)
);

COMMENT ON TABLE sod_violation IS
  'Design decision (FR-B-024 rule 2, AN-08): one row per employee found holding one entitlement matching sod_rule.group_a and one matching group_b, as observed in a specific access_snapshot. entitlement_id_a/entitlement_id_b reference entitlement_catalog directly (not snapshot_line) precisely so this table is NOT subject to the snapshot_line partitioned-table FOREIGN KEY limitation (Sec 7) -- a real FK here is fully enforceable and was chosen deliberately for that reason. Re-evaluation on every new snapshot (rule 2) is expected to find the same conflict again while it remains open; uq_sod_violation_open below prevents that from creating duplicate open rows.';

CREATE UNIQUE INDEX uq_sod_violation_open ON sod_violation (rule_id, employee_id, entitlement_id_a, entitlement_id_b) WHERE status = 'TERBUKA';
CREATE INDEX idx_sod_violation_employee_id ON sod_violation (employee_id);
CREATE INDEX idx_sod_violation_rule_id ON sod_violation (rule_id);
CREATE INDEX idx_sod_violation_status ON sod_violation (status);

-- ============================================================================
-- 16. sod_exception -- FR-B-025. Not detailed in the ERD relation diagram.
-- ============================================================================
CREATE TABLE sod_exception (
  id                   uuid PRIMARY KEY,
  violation_id         uuid NOT NULL REFERENCES sod_violation (id),
  business_reason      text NOT NULL,
  compensating_control text NOT NULL,
  approved_by          uuid NOT NULL REFERENCES app_user (id),
  approved_at          timestamptz NOT NULL DEFAULT now(),
  review_date          date NOT NULL,
  is_active            boolean NOT NULL DEFAULT true,
  created_at           timestamptz NOT NULL DEFAULT now(),
  -- FR-B-025 rule 1: review date at most 12 months out.
  CONSTRAINT chk_sod_exception_review_within_12_months CHECK (
    review_date <= (approved_at::date + INTERVAL '12 months')::date
  ),
  CONSTRAINT chk_sod_exception_review_after_approval CHECK (review_date > approved_at::date)
);

COMMENT ON TABLE sod_exception IS
  'Design decision (FR-B-025): approval for a specific sod_violation. business_reason and compensating_control are both NOT NULL (rule 1: both are mandatory on submission). Director-level approval for KRITIS-risk conflicts (rule 2) is NOT enforced here -- it requires checking the approver''s role/seniority against the violated rule''s risk_level, a cross-table authorization check that belongs in the application repository layer per CLAUDE.md''s "authorization filtering lives in the repository" rule. Automatic lapsing on review_date (rule 3) is a scheduled job reading this table, not a database trigger.';

CREATE UNIQUE INDEX uq_sod_exception_active ON sod_exception (violation_id) WHERE is_active;
CREATE INDEX idx_sod_exception_review_date ON sod_exception (review_date);

-- ============================================================================
-- 17. access_anomaly -- FR-B-007, ERD followed for the relation (one snapshot
-- has many anomalies); columns not detailed in the ERD.
-- ============================================================================
CREATE TABLE access_anomaly (
  id                    uuid PRIMARY KEY,
  snapshot_id           uuid NOT NULL REFERENCES access_snapshot (id),
  snapshot_line_id      uuid,
  employee_id           uuid REFERENCES employee (id),
  application_id        uuid NOT NULL REFERENCES application (id),
  code                  access_anomaly_code NOT NULL,
  severity              risk_level_type NOT NULL,
  first_detected_at     timestamptz NOT NULL DEFAULT now(),
  last_detected_at      timestamptz NOT NULL DEFAULT now(),
  status                finding_status NOT NULL DEFAULT 'TERBUKA',
  exception_reason      text,
  exception_review_date date,
  resolved_at           timestamptz,
  details               jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at            timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_access_anomaly_exception_consistency CHECK (
    status <> 'DIKECUALIKAN' OR (exception_reason IS NOT NULL AND exception_review_date IS NOT NULL)
  )
);

COMMENT ON TABLE access_anomaly IS
  'Design decision (FR-B-007): one row per detected anomaly (AN-01..AN-08) for a given snapshot. snapshot_line_id identifies the single triggering line where the anomaly is line-scoped (e.g. AN-01, AN-03, AN-04); it is nullable and, like every other reference into snapshot_line, carries no database FOREIGN KEY (Sec 7 deviation note). For anomalies spanning multiple lines (e.g. AN-06 duplicate accounts, AN-08 SoD -- which also gets its own richer row in sod_violation), the related line/account identifiers are recorded in details (jsonb) instead of forcing a single-line reference. employee_id is nullable for AN-02 (Tanpa Pemilik), where by definition no employee can be identified. FR-B-007 rule 3 ("umur dihitung sejak pertama terdeteksi") is implemented by the application preserving first_detected_at and only touching last_detected_at when the same anomaly reappears on a later snapshot -- matching by (application_id, code, employee_id/account) is an application-layer lookup, not a database constraint, since PostgreSQL has no natural key here stable enough to enforce.';

CREATE INDEX idx_access_anomaly_snapshot_id ON access_anomaly (snapshot_id);
CREATE INDEX idx_access_anomaly_application_code ON access_anomaly (application_id, code);
CREATE INDEX idx_access_anomaly_employee_id ON access_anomaly (employee_id);
CREATE INDEX idx_access_anomaly_status ON access_anomaly (status);

-- ============================================================================
-- 18. Application grants for every Modul B table.
--
-- Granting on the partitioned parent (snapshot_line) is sufficient for all
-- normal application access, regardless of whether the grant runs before or
-- after a given partition is created: PostgreSQL checks privileges against
-- the relation named in the query, and application code always queries
-- snapshot_line by its parent name, never an individual partition directly.
-- This was verified empirically against a live database (INSERT/SELECT as
-- sigap_app into a partition created by Sec 7''s bootstrap, which runs
-- BEFORE this GRANT in file order) -- see the task report, not just assumed.
-- ============================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON
  application,
  entitlement_catalog,
  connector,
  access_snapshot,
  snapshot_line,
  review_campaign,
  campaign_scope,
  review_item,
  review_decision,
  campaign_signoff,
  revocation_ticket,
  sod_rule,
  sod_violation,
  sod_exception,
  access_anomaly
TO sigap_app;
